# Generated by Django 3.0.3 on 2021-02-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uimage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
